"""
License endpoints for Enterprise license retrieval.

Provides endpoints for customers to retrieve their Enterprise licenses
from the Cloud SaaS dashboard.
"""

import logging
from typing import List, Optional
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from ...db.database import get_async_session
from ...models.user import User
from ...models.license import License, LicenseEdition, LicenseStatus
from ...services.license_generator_service import LicenseGeneratorService
from ..dependencies import get_current_user_jwt, require_saas

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/licenses", tags=["Licenses"])


# ============================================================================
# Pydantic Models
# ============================================================================

class LicenseResponse(BaseModel):
    """Response for a single license."""
    id: str
    license_key: str
    admin_token: Optional[str] = None  # Extracted from JWT for self-hosted admin setup
    edition: str
    status: str
    company_name: Optional[str] = None
    issued_at: str
    expires_at: Optional[str] = None
    features: List[str]
    order_id: Optional[str] = None

    class Config:
        from_attributes = True


def _extract_admin_token(license_key: str) -> Optional[str]:
    """
    Extract admin_token from LICENSE_KEY JWT payload.

    SECURITY NOTE: Signature verification is intentionally skipped here because:
    1. This JWT was generated by OUR LicenseGeneratorService and stored in our DB
    2. We are only reading the payload to extract the admin_token for display
    3. The actual license validation (with signature verification) happens at
       startup in core/edition.py when the Enterprise instance boots up
    4. This endpoint is SaaS-only (require_saas dependency) and auth-protected

    Args:
        license_key: The LICENSE_KEY JWT string (from our own database)

    Returns:
        The admin_token if found, None otherwise
    """
    try:
        import json
        import base64
        # Simple base64 decode of JWT payload - no crypto library needed
        # since we're reading our own trusted data from DB
        parts = license_key.split('.')
        if len(parts) != 3:
            return None
        # Add padding for base64
        payload_b64 = parts[1] + '=' * (4 - len(parts[1]) % 4)
        payload = json.loads(base64.urlsafe_b64decode(payload_b64))
        return payload.get("admin_token")
    except Exception as e:
        logger.warning(f"Failed to extract admin_token from license: {e}")
        return None


class LicensesListResponse(BaseModel):
    """Response for list of licenses."""
    licenses: List[LicenseResponse]
    count: int


# ============================================================================
# Endpoints
# ============================================================================

@router.get("/me", response_model=LicensesListResponse)
async def get_my_licenses(
    _: None = Depends(require_saas()),
    user: User = Depends(get_current_user_jwt),
    db: AsyncSession = Depends(get_async_session)
):
    """
    Get all Enterprise licenses for the current user.

    Returns licenses linked to the user's email address.
    This endpoint is only available on the Cloud SaaS platform.

    Use Case:
    - Enterprise customer purchases license via LemonSqueezy
    - Customer logs into SaaS dashboard
    - Customer retrieves their LICENSE_KEY to use in self-hosted deployment
    """
    if not user.email:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="User email required to retrieve licenses"
        )

    # Get all Enterprise licenses for this email
    licenses = await LicenseGeneratorService.get_licenses_by_email(db, user.email)

    # Build response
    license_responses = []
    for lic in licenses:
        # Extract features list from dict
        features = [k for k, v in lic.features.items() if v is True]

        # Extract admin_token from the JWT for self-hosted admin setup
        admin_token = _extract_admin_token(lic.license_key)

        license_responses.append(LicenseResponse(
            id=str(lic.id),
            license_key=lic.license_key,
            admin_token=admin_token,
            edition=lic.edition.value,
            status=lic.status.value,
            company_name=lic.company_name,
            issued_at=lic.issued_at.isoformat() if lic.issued_at else datetime.now().isoformat(),
            expires_at=lic.expires_at.isoformat() if lic.expires_at else None,
            features=features,
            order_id=lic.lemonsqueezy_order_id
        ))

    logger.info(f"User {user.email} retrieved {len(license_responses)} licenses")

    return LicensesListResponse(
        licenses=license_responses,
        count=len(license_responses)
    )


@router.get("/{license_id}", response_model=LicenseResponse)
async def get_license_by_id(
    license_id: str,
    _: None = Depends(require_saas()),
    user: User = Depends(get_current_user_jwt),
    db: AsyncSession = Depends(get_async_session)
):
    """
    Get a specific license by ID.

    Only returns the license if it belongs to the current user (by email).
    """
    from sqlalchemy import select
    from uuid import UUID

    try:
        license_uuid = UUID(license_id)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid license ID format"
        )

    # Query license
    result = await db.execute(
        select(License).where(License.id == license_uuid)
    )
    license_record = result.scalar_one_or_none()

    if not license_record:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="License not found"
        )

    # Verify ownership by email
    if license_record.customer_email != user.email:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You don't have access to this license"
        )

    # Extract features list
    features = [k for k, v in license_record.features.items() if v is True]

    # Extract admin_token from the JWT for self-hosted admin setup
    admin_token = _extract_admin_token(license_record.license_key)

    return LicenseResponse(
        id=str(license_record.id),
        license_key=license_record.license_key,
        admin_token=admin_token,
        edition=license_record.edition.value,
        status=license_record.status.value,
        company_name=license_record.company_name,
        issued_at=license_record.issued_at.isoformat() if license_record.issued_at else datetime.now().isoformat(),
        expires_at=license_record.expires_at.isoformat() if license_record.expires_at else None,
        features=features,
        order_id=license_record.lemonsqueezy_order_id
    )
