// ── Atoms ───────────────────────────────────────────────────────────────────
export { PhoneMockup } from './PhoneMockup'
export { Eyebrow } from './Eyebrow'
export { Tile } from './Tile'
export type { Integration } from './integrations'
export { INTEGRATIONS } from './integrations'

// ── Sections (v2 redesign) ──────────────────────────────────────────────────
export { OrbitalGateway } from './OrbitalGateway'
export { Hero } from './Hero'
export { StatStrip } from './StatStrip'
export { Problem } from './Problem'
export { HowItWorks } from './HowItWorks'
export { StepPanel } from './StepPanel'
export type { PanelKind } from './StepPanel'
export { Marketplace } from './Marketplace'
export { UseCases } from './UseCases'
export { Features } from './Features'
export { Workflows } from './Workflows'
export { Governance } from './Governance'
export { Comparison } from './Comparison'
export { NetworkBoundary } from './NetworkBoundary'
export { SelfHost } from './SelfHost'
export { Branding } from './Branding'
export { FinalCTA } from './FinalCTA'
export { Footer } from './Footer'
export { Nav } from './Nav'
